### ISSUE TITLE
New Dropbox API

### ISSUE THREAD

**Issue by mathstuf** [s-aska/dropbox-api-command#27]
Looks like Dropbox has a [new API](https://blogs.dropbox.com/developers/2015/04/a-preview-of-the-new-dropbox-api-v2/).

**Comment by s-aska** [comment]
:+1:

**Comment by danward79** [comment]
Does this still work with the new API?

**Comment by woodsb02** [comment]
According to dropbox, the API v1 will be disabled on 28th June 2017.
https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by s-aska** [comment]
Thank you for contacting me.
I will respond within two weeks.

**Comment by s-aska** [comment]
done :smiley: #29
