### ISSUE TITLE
Undefined subroutine in /usr/local/share/perl5/WebService/Dropbox.pm

### ISSUE THREAD

**Issue by fabiodj** [s-aska/dropbox-api-command#35]
CentOS installation

App::dropboxapi is up to date. (2.12)

# dropbox-api setup
Please Input API Key: ***************
Please Input API Secret: ***************
1. Open the Login URL: https://www.dropbox.com/oauth2/authorize?client_id=***************&response_type=code
2. Input code and press Enter: *********************************************

Undefined subroutine &HTTP::Request::Common::request_type_with_data called at /usr/local/share/perl5/WebService/Dropbox.pm line 242, <STDIN> line 3.

**Comment by s-aska** [comment]
A new HTTP::Message was added to the dependency.
Please check v2.13.

**Comment by fabiodj** [comment]
Many thanks s-aska,

Now it's okay
Its application to this development is exemplary.
